spring:
  application:
    name: helloservice-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8859
        dashboard: 127.0.0.1:8858
# 整合feign后, sentinel资源名为httpmethod:protocol://requesturl
feign:
  sentinel:
    enabled: true

server:
  port: 8006

# actuator
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      # 默认是 /actuator
      #      base-path: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      # 显示健康具体信息  默认不会显示详细信息
      show-details: always
