server:
  port: 8005

# actuator
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      # 默认是 /actuator
      #      base-path: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      # 显示健康具体信息  默认不会显示详细信息
      show-details: always

spring:
  cloud:
    gateway:
      #      discovery:
      #        locator:
      #          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
      #          enabled: true

      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）
        - id: provider_route
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://alibaba-consumer
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            - Path=/consumer/**
            - Method=GET
          # 过滤器（filters：过滤器，过滤规则）
          filters:
            ## 添加指定参数
            #            - AddRequestParameter=age, three
            # 去掉第一个path
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848