server:
  port: 10000
spring:
  application:
    name: ingress-service

eureka:
  instance:
    hostname: ingress-service
    prefer-ip-address: true
  client:
    eureka-server-port: 9999
    service-url:
      defaultZone: 'http://ingress-eureka:${eureka.client.eureka-server-port}/eureka/'