server:
  port: 8008

spring:
  application:
    name: kin-config
  cloud:
    config:
      server:
        #        git:
        #          uri: https://github.com/huangjianqin/kin-demo
        #          username:
        #          password:
        #          search-paths: /config
        native:
          search-locations: /Users/hjq/jvmapps/kin-demo/config

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8001/eureka,http://localhost:8002/eureka"