server:
  port: 8001
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  application:
    name: kin-diamond1

# actuator
management:
  server:
    port: 8001
  endpoints:
    web:
      # 默认是 /actuator
      #      base-path: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      # 显示健康具体信息  默认不会显示详细信息
      show-details: always

# eureka
eureka:
  instance:
    hostname: diamond1
  client:
    service-url:
      defaultZone: "http://localhost:8002/eureka"

turbine:
  # 监控的app唯一标识, 同时actuator也是使用默认的前缀/actuator, 因为turbine不支持自定义前缀改变的actuator
  app-config: kin-reference1,kin-reference2
  cluster-name-expression: new String("default")