server:
  port: 8006
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  application:
    name: kin-reference2

# actuator
management:
  server:
    port: 8006
  endpoints:
    web:
      # 默认是 /actuator
      #      base-path: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      # 显示健康具体信息  默认不会显示详细信息
      show-details: always

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 1500
#  OkToRetryOnAllOperations: true
#  MaxAutoRetriesNextServer: 3
#  MaxAutoRetries: 1
feign:
  hystrix:
    enabled: true
