server:
  port: 8002
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  application:
    name: kin-diamond2

# actuator
management:
  server:
    port: 8002
  endpoints:
    web:
      # 默认是 /actuator
      #      base-path: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      # 显示健康具体信息  默认不会显示详细信息
      show-details: always

# eureka
eureka:
  instance:
    hostname: diamond2
  client:
    service-url:
      defaultZone: "http://localhost:8001/eureka"

turbine:
  app-config: kin-reference1,kin-reference2
  cluster-name-expression: new String("default")