server:
  port: 8007
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  application:
    name: kin-zuul

# actuator
management:
  server:
    port: 8007
  endpoints:
    web:
      # 默认是 /actuator
      #      base-path: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      # 显示健康具体信息  默认不会显示详细信息
      show-details: always

# eureka
eureka:
  instance:
    hostname: kin-zuul

zuul:
  ignored-services: kin-reference1
#  routes:
#    ribbon:
#      path: /ribbon/**
#      serviceId: kin-reference1
#    feign:
#      path: /feign/**
#      serviceId: kin-reference2
#   更简洁的方式
#    kin-reference1:
#      /ribbon/**
#    kin-reference2:
#      /feign/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 1500