server:
  port: 9888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
          # true=开启用小写的serviceId 进行服务路由的转发
          lower-case-service-id: true

      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）
        - id: ingress-service-route
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://ingress-service/
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            - Path=/api/service/**
          # 过滤器（filters：过滤器，过滤规则）
          filters:
            ## 添加指定参数
            #    - AddRequestParameter=age, three
            # 去掉第一个path
            - StripPrefix=1
  application:
    name: ingress-gateway
  main:
    web-application-type: reactive

eureka:
  instance:
    hostname: ingress-gateway
    lease-renewal-interval-in-seconds: 15
    prefer-ip-address: true
  client:
    eureka-server-port: 9999
    service-url:
      defaultZone: 'http://ingress-eureka:${eureka.client.eureka-server-port}/eureka/'