server:
  port: 8005

# actuator
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      # 默认是 /actuator
      #      base-path: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      # 显示健康具体信息  默认不会显示详细信息
      show-details: always