spring:
  cloud:
    config:
      server:
        #        git:
        #          uri: https://github.com/huangjianqin/kin-demo
        #          username:
        #          password:
        #          search-paths: /config
        native:
          search-locations: /Users/hjq/jvmapps/kin-demo/config

