spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: "bigdata1:9092"
      binders:
        springcloudbus:
          destination:
            springcloudbus
        springcloudstream:
          destination:
            springcloudbus