spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: "bigdata1:9092"
      binders:
        input-in-0:
          destination:
            springcloudbus
        output:
          destination:
            springcloudbus